services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pswd
    volumes: 
      - /data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
     - 8080:8080
    depends_on:
      - db

volumes:
  db_data: